version: '3'

services:
  startupba-sql:
    image: mcr.microsoft.com/mssql/server:2022-CU26-ubuntu-22.04
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
    ports:
      - "1401:1433"
    expose:
      - 1433
    networks:
      - startupba-2025

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - startupba-2025

  startupba-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - SMTP__EMAIL=${SMTP__EMAIL}
      - SMTP__PASSWORD=${SMTP__PASSWORD}
    depends_on:
      - rabbitmq
      - startupba-sql
      - startupba-api
    networks:
      - startupba-2025
    ports:
      - 7111:80
  
  startupba-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=startupba-sql,1433;Database=${SQL__DATABASE};User Id=${SQL__USER};Password=${SQL__PASSWORD};ConnectRetryCount=0;TrustServerCertificate=True;
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - STRIPE__SECRET_KEY=${STRIPE__SECRET_KEY}
      - JWT__KEY=${JWT__KEY}
      - JWT__ISSUER=${JWT__ISSUER}
      - JWT__AUDIENCE=${JWT__AUDIENCE}
      - JWT__ACCESS_TOKEN_MINUTES=${JWT__ACCESS_TOKEN_MINUTES}
      - JWT__REFRESH_TOKEN_DAYS=${JWT__REFRESH_TOKEN_DAYS}
      - TZ=Europe/Zagreb
    ports:
      - "5130:5130"
    networks:
      - startupba-2025
    depends_on:
      - startupba-sql

networks:
  startupba-2025:
    driver: bridge